[package]
name = "rustpotter-cli"
version = "0.7.0"
edition = "2021"
license = "Apache-2.0"
description = "CLI for rustpotter, a personal keywords spotter written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustpotter = "0.7.0"
log = "0.4.6"
pv_recorder = "1.0.2"
ctrlc = "3.2.2"
clap = { version = "3.1.13", features = ["derive"] }
hound = "3.4.0"
include_dir = "0.7.2"
tempfile = "3.3.0"
simple_logger = "2.1.0"