[package]
name = "rustpotter-cli"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
description = "CLI for rustpotter, a personal keywords spotter written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustpotter = "0.2.0"
log = "0.4.6"
pv_recorder = "1.0.2"
ctrlc = "3.2.1"
clap = { version = "3.1.7", features = ["derive"] }
hound = "3.4.0"