[package]
name = "rustpotter-cli"
version = "1.0.1"
edition = "2021"
license = "Apache-2.0"
description = "CLI for Rustpotter, an open source wake word spotter forged in rust."
authors = ["Miguel Álvarez Díez <miguelwork92@gmail.com>"]
repository = "https://github.com/GiviMAD/rustpotter"

[dependencies]
rustpotter = { version = "1.0.1", features = ["files", "build", "log", "vad"] }
log = "0.4.6"
pv_recorder = "1.0.2"
ctrlc = "3.2.2"
clap = { version = "3.1.13", features = ["derive"] }
hound = "3.4.0"
include_dir = "0.7.2"
tempfile = "3.3.0"
simple_logger = "2.1.0"

[features]
default = []
# include recorder library into the binary for distribution outside cargo
dist = []